### ISSUE TITLE
List Index Out of Range

### ISSUE THREAD

**Issue by mzagaja** [MAPC/rental-listing-geolocator#3]
When running the geolocator on recent data we get the following error:
```sh
geolocator_1  | list index out of range
geolocator_1  | Traceback (most recent call last):
geolocator_1  |   File "geolocation_validation.py", line 515, in <module>
geolocator_1  |     mapzen_craigslist_merge.index = mapzen_craigslist.index
geolocator_1  |   File "/usr/local/lib/python2.7/site-packages/pandas/core/generic.py", line 5080, in __setattr__
geolocator_1  |     return object.__setattr__(self, name, value)
geolocator_1  |   File "pandas/_libs/properties.pyx", line 69, in pandas._libs.properties.AxisProperty.__set__
geolocator_1  |   File "/usr/local/lib/python2.7/site-packages/pandas/core/generic.py", line 638, in _set_axis
geolocator_1  |     self._data.set_axis(axis, labels)
geolocator_1  |   File "/usr/local/lib/python2.7/site-packages/pandas/core/internals/managers.py", line 155, in set_axis
geolocator_1  |     'values have {new} elements'.format(old=old_len, new=new_len))
geolocator_1  | ValueError: Length mismatch: Expected axis has 0 elements, new values have 8296 elements
```

**Comment by mzagaja** [comment]
>December export failed the geolocator even after surmounting the month 13 export bug earlier. I’m going to attempt Q4 to see if it works and then return to December. Otherwise will try to debug December first if Q4 also fails. I think the issues are related to the latitude/longitude updates that were implemented in development but never made it to production because I did not realize I needed to delete the docker image as well as kill the container to pull the change when I did it.
